language: cpp

env:
  matrix:
    - PY_VER=2.7
    - PY_VER=2.6

before_install:
  - sudo add-apt-repository -y ppa:fkrull/deadsnakes
  - sudo apt-get update
  - sudo apt-get install python$PY_VER python$PY_VER-dev python-virtualenv
  - sudo ls -laFh /usr/lib/libpython$PY_VER.so
  - virtualenv --python=`which python$PY_VER` .
  - source bin/activate
  - export PYTHONPATH=$PYTHONPATH:/home/travis/.local/lib/python$PY_VER/site-packages

# command to run tests
script: python$PY_VER test.py