language: cpp

env:
  matrix:
    - PY_VER=2.7
    - PY_VER=2.6

before_install:
  - sudo add-apt-repository -y ppa:fkrull/deadsnakes
  - sudo apt-get update
  - sudo apt-get install python$PY_VER

# command to run tests
script: python$PY_VER test.py